### ISSUE TITLE
SQL  ERROR upgrade 21.04.04 to 21.04.05

### ISSUE THREAD

**Issue by GuerchetM** [centreon/centreon#10166]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
centreon-21.04.5-1.el7.centos.noarch
centreon-auto-discovery-server-21.04.1-2.el7.centos.noarch
centreon-base-config-centreon-engine-21.04.5-1.el7.centos.noarch
centreon-broker-21.04.3-1.el7.centos.x86_64
centreon-broker-cbd-21.04.3-1.el7.centos.x86_64
centreon-broker-cbmod-21.04.3-1.el7.centos.x86_64
centreon-broker-core-21.04.3-1.el7.centos.x86_64
centreon-broker-debuginfo-21.04.3-1.el7.centos.x86_64
centreon-broker-devel-21.04.3-1.el7.centos.x86_64
centreon-broker-storage-21.04.3-1.el7.centos.x86_64
centreon-clib-21.04.2-1.el7.centos.x86_64
centreon-clib-debuginfo-21.04.2-1.el7.centos.x86_64
centreon-common-21.04.5-1.el7.centos.noarch
centreon-connector-21.04.2-4.el7.centos.x86_64
centreon-connector-as400-server-1.8.4-1.el7.centos.noarch
centreon-connector-debuginfo-21.04.2-4.el7.centos.x86_64
centreon-connector-perl-21.04.2-4.el7.centos.x86_64
centreon-connector-ssh-21.04.2-4.el7.centos.x86_64
centreon-database-21.04.5-1.el7.centos.noarch
centreon-devel-2-2.el7.centos.noarch
centreon-engine-21.04.3-5.el7.centos.x86_64
centreon-engine-daemon-21.04.3-5.el7.centos.x86_64
centreon-engine-debuginfo-21.04.3-5.el7.centos.x86_64
centreon-engine-extcommands-21.04.3-5.el7.centos.x86_64
centreon-fingerprint-21.04.0-2.el7.centos.x86_64
centreon-gorgone-21.04.2-1.el7.centos.noarch
centreon-gorgone-centreon-config-21.04.2-1.el7.centos.noarch
centreon-license-manager-21.04.0-1.el7.centos.noarch
centreon-license-manager-common-21.04.0-1.el7.centos.noarch
centreon-nrpe3-daemon-4.0.2-1.el7.centos.x86_64
centreon-nrpe3-debuginfo-4.0.2-1.el7.centos.x86_64
centreon-nrpe-daemon-2.15-4.el7.centos.x86_64
centreon-open-tickets-21.04.1-1.el7.centos.noarch
centreon-perl-libs-21.04.5-1.el7.centos.noarch
centreon-poller-centreon-engine-21.04.5-1.el7.centos.noarch
centreon-pp-manager-21.04.0-1.el7.centos.noarch
centreon-release-21.04-4.el7.centos.noarch
centreon-trap-21.04.5-1.el7.centos.noarch
centreon-web-21.04.5-1.el7.centos.noarch
centreon-widget-engine-status-21.04.0-1.el7.centos.noarch
centreon-widget-global-health-21.04.0-1.el7.centos.noarch
centreon-widget-graph-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-grid-map-21.04.0-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-host-monitoring-21.04.0-2.el7.centos.noarch
centreon-widget-httploader-21.04.0-3.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-21.04.0-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-21.04.0-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-service-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-tactical-overview-21.04.0-1.el7.centos.noarch
```

***Operating System***

*CentOS 7..*

***Browser used***

- [ ] Google Chrome
- [x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

I have tried tu update my centreon to 21.04.05 from 21.04.05 and i have the followin issue
![image](https://user-images.githubusercontent.com/24602644/134658959-2562fad3-d901-4e12-8630-0818d8a5d507.png)

 upgrade .log 👍 
```
2021-09-24 12:07|0|0|UPGRADE - 21.04.5:Impossible to alter the table contact - Code : 270336 - Error : SQLSTATE[42000]: Syntax error or a
ccess violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storag
e overhead, check the manual. You have to change some columns to TEXT or BLOBs - Trace : #0 /usr/share/centreon/www/install/php/Update-21
.04.5.php(38): CentreonDB->query('ALTER TABLE co...')
#1 /usr/share/centreon/www/install/step_upgrade/process/process_step4.php(72): include_once('/usr/share/cent...')
#2 {main}
```

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. I reached the Custom View
3. And so on...

### Logs

**PHP error logs**

For version using PHP 7.2 on centOs 7
```
24-Sep-2021 12:11:28 Europe/Paris] PHP Warning:  require_once(/usr/share/centreon/GPL_LIB/Smarty/libs/Smarty.class.php): failed to open stream: No such file or directory in /usr/share/centreon/www/widgets/centreon-widget-alrt/index.php on line 8
[24-Sep-2021 12:11:28 Europe/Paris] PHP Warning:  require_once(/usr/share/centreon/GPL_LIB/Smarty/libs/Smarty.class.php): failed to open stream: No such file or directory in /usr/share/centreon/www/widgets/centreon-widget-alrt/index.php on line 8
[24-Sep-2021 12:11:28 Europe/Paris] PHP Fatal error:  require_once(): Failed opening required '/usr/share/centreon/GPL_LIB/Smarty/libs/Smarty.class.php' (include_path='.:/opt/rh/rh-php73/root/usr/share/pear:/opt/rh/rh-php73/root/usr/share/php') in /usr/share/centreon/www/widgets/centreon-widget-alrt/index.php on line 8
[24-Sep-2021 12:11:28 Europe/Paris] PHP Fatal error:  require_once(): Failed opening required '/usr/share/centreon/GPL_LIB/Smarty/libs/Smarty.class.php' (include_path='.:/opt/rh/rh-php73/root/usr/share/pear:/opt/rh/rh-php73/root/usr/share/php') in /usr/share/centreon/www/widgets/centreon-widget-alrt/index.php on line 8
[24-Sep-2021 12:16:29 Europe/Paris] PHP Warning:  require_once(/usr/share/centreon/GPL_LIB/Smarty/libs/Smarty.class.php): failed to open stream: No such file or directory in /usr/share/centreon/www/widgets/centreon-widget-alrt/index.php on line 8
[24-Sep-2021 12:16:29 Europe/Paris] PHP Fatal error:  require_once(): Failed opening required '/usr/share/centreon/GPL_LIB/Smarty/libs/Smarty.class.php' (include_path='.:/opt/rh/rh-php73/root/usr/share/pear:/opt/rh/rh-php73/root/usr/share/php') in /usr/share/centreon/www/widgets/centreon-widget-alrt/index.php on line 8
[24-Sep-2021 12:16:29 Europe/Paris] PHP Warning:  require_once(/usr/share/centreon/GPL_LIB/Smarty/libs/Smarty.class.php): failed to open stream: No such file or directory in /usr/share/centreon/www/widgets/centreon-widget-alrt/index.php on line 8
[24-Sep-2021 12:16:29 Europe/Paris] PHP Fatal error:  require_once(): Failed opening required '/usr/share/centreon/GPL_LIB/Smarty/libs/Smarty.class.php' (include_path='.:/opt/rh/rh-php73/root/usr/share/pear:/opt/rh/rh-php73/root/usr/share/php') in /usr/share/centreon/www/widgets/centreon-widget-alrt/index.php on line 8

```

**Comment by Blubmann1337** [comment]
Had the same problem:

2021-09-27 14:46|0|0|UPGRADE - 21.04.5:Impossible to alter the table contact - Code : 270336 - Error : SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs - Trace : #0 /usr/share/centreon/www/install/php/Update-21.04.5.php(38): CentreonDB->query('ALTER TABLE co...')
#1 /usr/share/centreon/www/install/step_upgrade/process/process_step4.php(72): include_once('/usr/share/cent...')

**Comment by gagzou** [comment]
+1 for me, same problem for 20.10.10 > 20.10.11

**Comment by dreygaurez-vivacy** [comment]
I had the same problem, 20.10.10 > 20.10.11.
I solved it by reducing the size of one column I don't use in the `contact` table.
You can get the VARCHAR columns by running `DESC contact` on the database.
I then ran the following SQL query on the `centreon` database:
`ALTER TABLE contact MODIFY <column to reduce> VARCHAR(50)`
It is not the best solution though, as it alters the original schema database.
It may be necessary to set it back to the original size during a future update as it could cause errors.

**Comment by ponchoh** [comment]
please try/check the row format on every table:

```sql
SELECT table_schema,table_name,row_format FROM information_schema.tables WHERE table_schema IN ("centreon", "centreon_storage") ORDER BY table_schema;
```

Update from compact to dynamic:

```bash
### For centreon database ###
mysql --batch --skip-column-names --execute 'SELECT CONCAT("ALTER TABLE `", table_name, "` ROW_FORMAT=dynamic;") AS aQuery FROM information_schema.tables WHERE table_schema = "centreon"' | mysql centreon

### For centreon_storage ###
mysql --batch --skip-column-names --execute 'SELECT CONCAT("ALTER TABLE `", table_name, "` ROW_FORMAT=dynamic;") AS aQuery FROM information_schema.tables WHERE table_schema = "centreon_storage"' | mysql centreon_storage  
```

@GuerchetM let me know

**Comment by gagzou** [comment]
@ponchoh 
It works !

**Comment by lpinsivy** [comment]
Thank you @ponchoh for your workaround.

Will be fixed by PR #10250
