### ISSUE TITLE
Can not login after upgrade

### ISSUE THREAD

**Issue by zskarman** [centreon/centreon#3479]
Dear Team,

I have an running 22.10.5 and when I try to upgrade to 23.10.9 getting this error:
`Unexpected Application Error!
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rs (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:116368)
    at d (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:57770)
    at h (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:59125)
    at e (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:61182)
    at wo (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:72834)
    at Ei (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:121524)
    at ks (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:108865)
    at ys (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:108793)
    at vs (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:108656)
    at us (http://127.0.0.1:280/centreon/static/422.54a5f503.chunk.js:2:105463)`

It looks some of SQL tables are not updated as it need.
When I export original 23.10 centreon schema and import to an updated node, it works.
But If I run standard process get error.
Can you please check which table / content is required to resolve that issue?

Regards, Zsolt

**Comment by zskarman** [comment]
Hi Team, Shall I get any help on this issue?
Regards, Zsolt

**Comment by lpinsivy** [comment]
Look like a browser cache issue
