### ISSUE TITLE
Host/Service macros not visible in service/host form when command has > 200 macros

### ISSUE THREAD

**Issue by flex-pgum** [centreon/centreon#4668]
# BUG REPORT INFORMATION

### Prerequisites

Affects all centreon versions (tested on latest centreon-web 22.10 + 23.10) and by viewing the code also the current develop branch is affected

### Description

Problems:
1. It is not possible to create a service template or a service with more than 200 macros (by hand)

2. When a command is selected in the service template form and the command has > 200 macros no macros are displayed:
![image](https://github.com/user-attachments/assets/cfebdb39-6497-4a9f-916f-3a46568c4271)

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Create a new command with 250 service macros in the command line
3. Add new service template and select the previously created command

### Describe the received result

![image](https://github.com/user-attachments/assets/cfebdb39-6497-4a9f-916f-3a46568c4271)

### Logs

No relevant php/sql logs but a browser console log:

```
jquery.min.js:2 Uncaught TypeError: form.data is not a function
    at String.<anonymous> (jquery.sheepItPlugin.min.js:982:38)
    at Function.each (jquery.min.js:2:3026)
    at fillForm (jquery.sheepItPlugin.min.js:979:15)
    at S.fn.init.fillData (jquery.sheepItPlugin.min.js:959:17)
    at Object.i (jquery.min.js:2:88736)
    at Function.each (jquery.min.js:2:2976)
    at S.fn.init.inject (jquery.sheepItPlugin.min.js:1379:27)
    at initialize (jquery.sheepItPlugin.min.js:1225:24)
    at jQuery.fn.sheepIt (jquery.sheepItPlugin.min.js:1537:9)
    at HTMLDocument.<anonymous> (main.get.php?p=60206&o=c&service_id=1128:984:32)
```

### Possible fix

I did some investigation and the error is produced because the jQuery plugin sheepIt was initialized with `maxFormsCount: 200` on both `formService.ihtml` and `formHost.ihtml`.

My suggestion is to set `maxFormsCount` to `0` (no limit) to prevent this error from happening (obviously having >200 macros is a very rare case but if this happens, there won't be/are problems).

Files where the modification has to be done:

- `centreon/www/include/configuration/configObject/service/formService.ihtml`  line 500 (22.10/23.10) / `centreon/www/include/configuration/configObject/service/formServiceOnPrem.ihtml` line 500 (24.04+)
- `centreon/www/include/configuration/configObject/host/formHost.ihtml` line 620 (22.10/23.10) / `centreon/www/include/configuration/configObject/host/formHostOnPrem.ihtml` line 620 (24.04+)

**Comment by lpinsivy** [comment]
Hi @flex-pgum, thank you for your feedback.
In which case do you have more than 200 custom macros in one command?

**Comment by flex-pgum** [comment]
We have a command using the plugin apps-varnish-local.pl and have configured service macros for all possible options which can be provided to the plugin (>200). On the service template using the command, most of the macros are not set, but saving the template or a service inheriting such template does not work due to the limitation.
