### ISSUE TITLE
[CLAPI] Fatal error with PDOException

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#5453]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.9

Hi 
I can't setparam 'geo_coords' on HG with CLAPI

```
HG;setparam;Linux;geo_coords;36.52,4.87

PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hg_geo_coords' in 'field list'' in /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php:228

Stack trace:
#0 /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /usr/share/centreon/lib/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/centreon/lib/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /usr/share/centreon/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE hostgrou...', Array)
#4 /usr/share/centreon/lib/Centreon/Object/Object.php(198): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE hostgrou...', Array)
#5 /usr/share/centreon/www/class/centreon-clapi/centreonObject.class.php(269): Centreon_Object->update('1190', Array)
#6 /usr/share/centreon/www/class/centreon-clapi/centreonHostGroup.class.php(159): CentreonClapi\CentreonObject->setparam('1190', Array)
#7 /usr/share/centreon/www/class/c in /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php on line 234
```

Best Regards

**Comment by roysha1** [comment]
Hi @lpinsivy ,

Im experiencing the same issue with 2.8.29, my code is updated with the above fix.

```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cg_ar_id' in 'field list'' in /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /usr/share/centreon/lib/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/centreon/lib/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /usr/share/centreon/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE contactg...', Array)
#4 /usr/share/centreon/lib/Centreon/Object/Object.php(198): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE contactg...', Array)
#5 /usr/share/centreon/www/class/centreon-clapi/centreonObject.class.php(326): Centreon_Object->update('6', Array)
#6 /usr/share/centreon/www/class/centreon-clapi/centreonContactGroup.class.php(135): CentreonClapi\CentreonObject->setparam('6', Array)
#7 /usr/share/centreon/www/class/centreon- in /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php on line 234
```
Thanks!
