### ISSUE TITLE
OpenID column `token` too small

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#6168]
# BUG REPORT INFORMATION

### Description

We have configured SSO OpenID. Some users have many roles (more than 50). They cannot connect on centreon.

We have the following error in ```centreon-web.log```:
```
[2024-12-18T10:22:33+0100] [ERROR] [Core\Security\Authentication\Infrastructure\Repository\DbWriteTokenRepository:80]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'token' at row 1 {"trace":"#0 /usr/share/centreon/src/Core/Security/Authentication/Infrastructure/Repository/DbWriteTokenRepository.php(221): PDOStatement->execute()\n#1 /usr/share/centreon/src/Core/Security/Authentication/Infrastructure/Repository/DbWriteTokenRepository.php(179): Core\\Security\\Authentication\\Infrastructure\\Repository\\DbWriteTokenRepository->insertSecurityToken()\n#2 /usr/share/centreon/src/Core/Security/Authentication/Infrastructure/Repository/DbWriteTokenRepository.php(67): Core\\Security\\Authentication\\Infrastructure\\Repository\\DbWriteTokenRepository->insertProviderTokens()\n#3 /usr/share/centreon/src/Core/Security/Authentication/Application/UseCase/Login/Login.php(202): Core\\Security\\Authentication\\Infrastructure\\Repository\\DbWriteTokenRepository->createAuthenticationTokens()\n#4 /usr/share/centreon/src/Core/Security/Authentication/Application/UseCase/Login/Login.php(132): Core\\Security\\Authentication\\Application\\UseCase\\Login\\Login->createAuthenticationTokens()\n#5 /usr/share/centreon/src/Core/Security/Authentication/Infrastructure/Api/Login/OpenId/LoginController.php(60): Core\\Security\\Authentication\\Application\\UseCase\\Login\\Login->__invoke()\n#6 /usr/share/centreon/vendor/symfony/http-kernel/HttpKernel.php(181): Core\\Security\\Authentication\\Infrastructure\\Api\\Login\\OpenId\\LoginController->__invoke()\n#7 /usr/share/centreon/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#8 /usr/share/centreon/vendor/symfony/http-kernel/Kernel.php(197): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#9 /usr/share/centreon/api/index.php(47): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#10 {main}"}
```

If we change the column size, it's working:
```
mysql> ALTER TABLE security_token MODIFY COLUMN token TEXT;
```

**Comment by lpinsivy** [comment]
Hi @garnier-quentin on which version did you have this problem?

Current size is varchar(4096):
```
CREATE TABLE `security_token` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `token` varchar(4096) NOT NULL,
  `creation_date` bigint UNSIGNED NOT NULL,
  `expiration_date` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `expiration_index` (`expiration_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
https://github.com/centreon/centreon/blob/develop/centreon/www/install/createTables.sql#L2384
