### ISSUE TITLE
Bad permissions on centreon-web.log

### ISSUE THREAD

**Issue by jderrien** [centreon/centreon#6211]
# BUG REPORT INFORMATION

### Prerequisites

***Module version***
```
ii  centreon-central 24.10.3-1+deb12u1 all          The package contains base configuration for Centreon Engine and Centreon Broker.
ii  centreon-web     24.10.3-1+deb12u1 all          This package contains WebUI files.```
```
***Operating System***
Debian 12

***Additional environment details:***
Fresh installation with `apt-get install centreon-central`

### Description

`/var/log/centreon/centreon-web.log` is created during the web installation process with the following permissions:
```
-rw-r--r-- 1 centreon centreon 10824 Dec 20 10:17 /var/log/centreon/centreon-web.log
```

After that, the web UI cannot log into it.

A possible fix would be to make it writable by `www-data` as follows:
```
chown www-data:www-data /var/log/centreon/centreon-web.log
chmod 664 /var/log/centreon/centreon-web.log
```

This will also allow the cron jobs (executed by the `centreon` user) to log into it. For example, the following cron needs it:
```
# Cron for Outdated Token removal
* * * * * centreon /usr/share/centreon/cron/outdated-token-removal.php >> /var/log/centreon/centreon-tokens.log 2>&1
```

### Steps to Reproduce

1. Log in Centreon with bad credentials

### Describe the received result

Errors are displayed in the web UI stating the log file cannot be opened.

### Describe the expected result

* The web UI should display: `Authentication failed`
* Errors should be logged into `/var/log/centreon/centreon-web.log`

### Logs

Error messages displayed in the web UI:
```
The stream or file "/var/log/centreon/centreon-web.log" could not be opened in append mode: chmod(): Operation not permitted The exception occurred while attempting to log: [Core\Security\Authentication\Infrastructure\Api\Login\Local\LoginController:73]: The stream or file "/var/log/centreon/centreon-web.log" could not be opened in append mode: chmod(): Operation not permitted The exception occurred while attempting to log: [Core\Security\Authentication\Application\UseCase\Login\Login:153]: An error occurred during authentication Context: {"trace":"Core\\Security\\Authentication\\Domain\\Exception\\AuthenticationException: Authentication failed in \/usr\/share\/centreon\/src\/Core\/Security\/Authentication\/Domain\/Exception\/AuthenticationException.php:33\nStack trace:\n#0 \/usr\/share\/centreon\/src\/Security\/Domain\/Authentication\/Model\/LocalProvider.php(156): Core\\Security\\Authentication\\Domain\\Exception\\AuthenticationException::notAuthenticated()\n#1 \/usr\/share\/centreon\/src\/Core\/Security\/Authentication\/Infrastructure\/Provider\/Local.php(71): Security\\Domain\\Authentication\\Model\\LocalProvider->authenticateOrFail()\n#2 \/usr\/share\/centreon\/src\/Core\/Security\/Authentication\/Application\/UseCase\/Login\/Login.php(97): Core\\Security\\Authentication\\Infrastructure\\Provider\\Local->authenticateOrFail()\n#3 \/usr\/share\/centreon\/src\/Core\/Security\/Authentication\/Infrastructure\/Api\/Login\/Local\/LoginController.php(71): Core\\Security\\Authentication\\Application\\UseCase\\Login\\Login->__invoke()\n#4 \/usr\/share\/centreon\/vendor\/symfony\/http-kernel\/HttpKernel.php(181): Core\\Security\\Authentication\\Infrastructure\\Api\\Login\\Local\\LoginController->__invoke()\n#5 \/usr\/share\/centreon\/vendor\/symfony\/http-kernel\/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#6 \/usr\/share\/centreon\/vendor\/symfony\/http-kernel\/Kernel.php(197): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#7 \/usr\/share\/centreon\/api\/index.php(47): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#8 {main}"}
```
```
The stream or file "/var/log/centreon/centreon-web.log" could not be opened in append mode: chmod(): Operation not permitted The exception occurred while attempting to log: [Core\Security\Authentication\Infrastructure\Api\Login\Local\LoginController:73]: The stream or file "/var/log/centreon/centreon-web.log" could not be opened in append mode: chmod(): Operation not permitted The exception occurred while attempting to log: [Core\Security\Authentication\Application\UseCase\Login\Login:153]: An error occurred during authentication Context: {"trace":"Core\\Security\\Authentication\\Domain\\Exception\\AuthenticationException: Authentication failed in \/usr\/share\/centreon\/src\/Core\/Security\/Authentication\/Domain\/Exception\/AuthenticationException.php:33\nStack trace:\n#0 \/usr\/share\/centreon\/src\/Security\/Domain\/Authentication\/Model\/LocalProvider.php(156): Core\\Security\\Authentication\\Domain\\Exception\\AuthenticationException::notAuthenticated()\n#1 \/usr\/share\/centreon\/src\/Core\/Security\/Authentication\/Infrastructure\/Provider\/Local.php(71): Security\\Domain\\Authentication\\Model\\LocalProvider->authenticateOrFail()\n#2 \/usr\/share\/centreon\/src\/Core\/Security\/Authentication\/Application\/UseCase\/Login\/Login.php(97): Core\\Security\\Authentication\\Infrastructure\\Provider\\Local->authenticateOrFail()\n#3 \/usr\/share\/centreon\/src\/Core\/Security\/Authentication\/Infrastructure\/Api\/Login\/Local\/LoginController.php(71): Core\\Security\\Authentication\\Application\\UseCase\\Login\\Login->__invoke()\n#4 \/usr\/share\/centreon\/vendor\/symfony\/http-kernel\/HttpKernel.php(181): Core\\Security\\Authentication\\Infrastructure\\Api\\Login\\Local\\LoginController->__invoke()\n#5 \/usr\/share\/centreon\/vendor\/symfony\/http-kernel\/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#6 \/usr\/share\/centreon\/vendor\/symfony\/http-kernel\/Kernel.php(197): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#7 \/usr\/share\/centreon\/api\/index.php(47): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#8 {main}"}
```

**Comment by lpinsivy** [comment]
Hi @jderrien thank you for your feedback.

Internal ticket MON-156026
