### ISSUE TITLE
Unable to duplicate service

### ISSUE THREAD

**Issue by bbnono** [centreon/centreon#7111]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  18.10.2

**Centreon Engine version**: 18.10.0

**Centreon Broker version**: 18.10.1

**OS**: CentOS Linux release 7.6.1810

**Additional environment details (AWS, VirtualBox, physical, etc.): **
Apache/2.4.37
PHP 7.2.13
mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64)

**Steps to reproduce the issue:**
1. On  Configuration  >  Services  >  Services by host 
2. Select a service and choose duplicate

**Describe the results you received:**
only menu are display, center page is blank

**Describe the results you expected:**
I expected a duplicate service

**Additional information you think important (e.g. issue happens only occasionally):**
On apache logs, i found this :
AH01071: Got error 'PHP message: PHP Warning:  file_put_contents(/var/log/centreon/sql-error.log): failed to open stream: Permission denied in /usr/share/centreon/www/class/centreonLog.class.php on line 187\nPHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'hsr_id' at row 1 in /usr/share/centreon/www/class/centreonDB.class.php:262\nStack trace:\n#0 /usr/share/centreon/www/include/configuration/configObject/service/DB-Func.php(587): CentreonDB->query('INSERT INTO hos...')\n#1 /usr/share/centreon/www/include/configuration/configObject/service/serviceByHost.php(139): multipleServiceInDB(Array, Array)\n#2 /usr/share/centreon/www/main.get.php(246): include_once('/usr/share/cent...')\n#3 {main}\n  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 262\n', referer: https://my.url/main.get.php?p=60201

**Comment by bbnono** [comment]
Sorry for this issue, I found the issue
Mysql 5.7 requires order by clause in select DISTINCT statement, just adapt the sql_mode
