### ISSUE TITLE
Error during import of contacts and/or contact groups

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon#7783]
Centreon 19.04.3

When importing contacts or contactgroups :

PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 **Unknown column 'cg_ar_id' in 'field list'** in /usr/share/centreon/www/class/centreonDB.class.php:267
Stack trace:
#0 /usr/share/centreon/lib/Centreon/Object/Object.php(178): CentreonDB->query('UPDATE contactg...', Array)
#1 /usr/share/centreon/www/class/centreon-clapi/centreonObject.class.php(365): Centreon_Object->update('2400', Array)
#2 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(806): CentreonClapi\CentreonObject->setparam('HM_NAGIOS_UNIX;...')
#3 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(769): CentreonClapi\CentreonAPI->launchActionForImport()
#4 /usr/share/centreon/bin/centreon(200): CentreonClapi\CentreonAPI->import('centreon-clapi-...')
#5 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 267

In the CLAPI file only "ar_id" is found, no "cg_ar_id", in the code too, I didn’t find  where it could come from…

Also, why is this field the only one which is not prefixed with "cg_" in the contactgroup table ?

**Comment by lpinsivy** [comment]
Hi @StefThomas maybe we have an issue when we export the contact table in CLAPI and we didn't remove the cg_ from cg_ar_id field.

If you remove the import works?

**Comment by StefThomas** [comment]
No, I looked into the exported file, I found only 'ar_id' ,no 'cg_ar_id'. I have to remove all those lines (which contain 'ar_id') : CG and CONTACT, for the import to work.


Stéphane THOMAS

ETL & Outils – DOT

Harmonie Mutuelle

☎ +332 47 46 52 87

________________________________
De : Laurent Pinsivy <notifications@github.com>
Envoyé : lundi 19 août 2019 10:54
À : centreon/centreon <centreon@noreply.github.com>
Cc : THOMAS Stéphane <Stephane.THOMAS@harmonie-mutuelle.fr>; Mention <mention@noreply.github.com>
Objet : Re: [centreon/centreon] Error during import of contacts and/or contact groups (#7783)


Hi @StefThomas<https://github.com/StefThomas> maybe we have an issue when we export the contact table in CLAPI and we didn't remove the cg_ from cg_ar_id field.

If you remove the import works?
