### ISSUE TITLE
Problem after migration 19.10.0 rc 1 to 19.10.1

### ISSUE THREAD

**Issue by mickaeldecastro** [centreon/centreon#8020]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***
Centreon 19.10.1

For the deb based systems

-- Copy/Paste the result of the following command --
```
$ rpm -qa  | grep centreon
centreon-web-19.10.1-3.el7.centos.noarch
centreon-engine-daemon-19.10.0-2.el7.centos.x86_64
centreon-broker-cbd-19.10.0-1.el7.centos.x86_64
centreon-widget-engine-status-19.10.0-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-19.10.0-1.el7.centos.noarch
centreon-widget-tactical-overview-19.10.0-1.el7.centos.noarch
centreon-license-manager-common-19.10.0-1.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20191016-111959.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20191016-111959.el7.centos.noarch
centreon-broker-graphite-19.10.0-1.el7.centos.x86_64
centreon-release-19.10-1.el7.centos.noarch
centreon-connector-ssh-19.10.0-1558340753.1d0c3c0.el7.centos.x86_64
centreon-connector-19.10.0-1558340753.1d0c3c0.el7.centos.x86_64
centreon-perl-libs-19.10.1-3.el7.centos.noarch
centreon-broker-19.10.0-1.el7.centos.x86_64
centreon-broker-storage-19.10.0-1.el7.centos.x86_64
centreon-engine-extcommands-19.10.0-2.el7.centos.x86_64
centreon-broker-cbmod-19.10.0-1.el7.centos.x86_64
centreon-widget-host-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-grid-map-19.10.0-1.el7.centos.noarch
centreon-widget-httploader-19.10.0-1.el7.centos.noarch
centreon-widget-graph-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-19.10.0-1.el7.centos.noarch
centreon-trap-19.10.1-3.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20191016-111959.el7.centos.noarch
centreon-license-manager-19.10.0-1.el7.centos.noarch
centreon-auto-discovery-server-19.10.0-2.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20191016-111959.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20191016-111959.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20191016-111959.el7.centos.noarch
centreon-poller-centreon-engine-19.10.1-3.el7.centos.noarch
centreon-19.10.1-3.el7.centos.noarch
centreon-clib-19.10.0-1565192555.f3cdb1c.el7.centos.x86_64
centreon-connector-perl-19.10.0-1558340753.1d0c3c0.el7.centos.x86_64
centreon-common-19.10.1-3.el7.centos.noarch
centreon-broker-core-19.10.0-1.el7.centos.x86_64
centreon-engine-19.10.0-2.el7.centos.x86_64
centreon-widget-service-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-global-health-19.10.0-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20191016-111959.el7.centos.noarch
centreon-pp-manager-19.10.0-5.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20191016-111959.el7.centos.noarch
centreon-database-19.10.1-3.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20191016-111959.el7.centos.noarch
centreon-base-config-centreon-engine-19.10.1-3.el7.centos.noarch
```
***Operating System***

CentOS 7.7

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

After the migration from 19.10.0-rc.1 tp 19.10.1 I have 2 errors when I want to export configuration to a poller. 
When I have Run monitoring engine debug (-v) enable:
- sh: : command not found
When I want check option Restart Monitoring Engine
- (SQLSTATE[42S22]: Column not found: 1054 Unknown column 'broker_reload_command' in 'field list') |  

In database field broker_reload_command missing. 

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.
1. Update centreon from 19.10.0 rc 1 to 19.10.1
2. Follow the wizard to migrate centreon
3. Try to export/reload poller 

### Describe the received result

1- 

Preparing environment... OKGenerating files... NOKAborted. | [ - ] poller sh: : command not found
-- | --

2-
Progress (50%) |  
-- | --
Preparing environment... OKGenerating files... OKRestarting engine... NOK (SQLSTATE[42S22]: Column not found: 1054 Unknown column 'broker_reload_command' in 'field list') |  
Errors/warnings in restart

### Logs
** PHP
I have the following error when I try to update poller configuration to add broker_reload_command paramter.

[21-Oct-2019 10:33:05 Europe/Paris] PHP Warning:  file_put_contents(/var/log/centreon/sql-error.log): failed to open stream: Permission denied in /usr/share/centreon/www/class/centreonLog.class.php on line 187
[21-Oct-2019 10:33:05 Europe/Paris] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'engine_start_command' in 'field list' in /usr/share/centreon/www/class/centreonDB.class.php:274
Stack trace:
#0 /usr/share/centreon/www/include/configuration/configServers/DB-Func.php(751): CentreonDB->query('UPDATE `nagios_...')
#1 /usr/share/centreon/www/include/configuration/configServers/formServers.php(388): updateServer(2, Array)
#2 /usr/share/centreon/www/include/configuration/configServers/servers.php(102): require_once('/usr/share/cent...')
#3 /usr/share/centreon/www/main.get.php(248): include_once('/usr/share/cent...')
#4 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 274
**centreon-engine logs (*if needed*)**

**Comment by lpinsivy** [comment]
Hi @mickaeldecastro ,

The Centreon 19.10.0-beta.3 added new fields in 'nagios_server' table: https://github.com/centreon/centreon/blob/f77a0a5036b9a685d2550ef066abbe4d4f8426d0/www/install/php/Update-19.10.0-beta.3.php#L155

Do you have SQL errors in /var/log/centreon/sql-error.log during update process?
Do you have PHP errors in /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log during update process?

Regards,

**Comment by mickaeldecastro** [comment]
Hi @lpinsivy 

Thanks for you reply.
I had only the following sql error.
```
2019-10-14 12:29|0|0| QUERY : INSERT INTO on_demand_macro_host (host_host_id,host_macro_name,host_macro_value,is_password,description,macro_order) VALUES (?,?,?,?,?,?), ["34","$_HOSTVAULTURL$","http:\/\/vault-svc.default","","","1"]
2019-10-14 12:29|0|0| QUERY : INSERT INTO on_demand_macro_host (host_host_id,host_macro_name,host_macro_value,is_password,description,macro_order) VALUES (?,?,?,?,?,?), ["34","$_HOSTVAULTURL$","http:\/\/vault-svc.default","","","1"]
2019-10-14 12:32|0|0| QUERY : INSERT INTO on_demand_macro_host (host_host_id,host_macro_name,host_macro_value,is_password,description,macro_order) VALUES (?,?,?,?,?,?), ["34","$_HOSTVAULTURL$","http:\/\/vault-svc.default","","","1"]```

And for centreon-error.log

```
14-Oct-2019 09:08:59 Europe/Paris] PHP Notice:  Undefined variable: l_rndcolor in /usr/share/centreon/www/class/centreonGraphNg.class.php on line 1119
[14-Oct-2019 09:08:59 Europe/Paris] PHP Notice:  Undefined variable: l_rndcolor in /usr/share/centreon/www/class/centreonGraphNg.class.php on line 1119
[14-Oct-2019 09:51:07 Europe/Paris] PHP Warning:  Illegal string offset 'command_type' in /usr/share/centreon/www/include/configuration/configObject/command/minCommand.php on line 132
[14-Oct-2019 09:51:39 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1484
[14-Oct-2019 09:51:39 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1484
[14-Oct-2019 09:51:39 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1484
[14-Oct-2019 09:51:39 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1484
[14-Oct-2019 09:51:39 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1145
[14-Oct-2019 09:51:39 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1145
[14-Oct-2019 09:51:42 Europe/Paris] PHP Warning:  Illegal string offset 'command_type' in /usr/share/centreon/www/include/configuration/configObject/command/minCommand.php on line 132
[14-Oct-2019 09:51:58 Europe/Paris] PHP Warning:  Illegal string offset 'command_type' in /usr/share/centreon/www/include/configuration/configObject/command/minCommand.php on line 132
[14-Oct-2019 09:53:47 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1484
[14-Oct-2019 09:53:47 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1484
[14-Oct-2019 09:53:47 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1484
[14-Oct-2019 09:53:47 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1484
[14-Oct-2019 09:53:47 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1145
[14-Oct-2019 09:53:47 Europe/Paris] PHP Notice:  Undefined index: macroFrom in /usr/share/centreon/www/class/centreonHost.class.php on line 1145
[14-Oct-2019 11:12:57 Europe/Paris] PHP Warning:  Illegal string offset 'command_type' in /usr/share/centreon/www/include/configuration/configObject/command/minCommand.php on line 132
[14-Oct-2019 11:14:24 Europe/Paris] PHP Warning:  Illegal string offset 'command_type' in /usr/share/centreon/www/include/configuration/configObject/command/minCommand.php on line 132
[14-Oct-2019 11:14:37 Europe/Paris] PHP Warning:  Illegal string offset 'command_type' in /usr/share/centreon/www/include/configuration/configObject/command/minCommand.php on line 132
[14-Oct-2019 11:18:26 Europe/Paris] PHP Warning:  Illegal string offset 'command_type' in /usr/share/centreon/www/include/configuration/configObject/command/minCommand.php on line 132
[14-Oct-2019 11:54:00 Europe/Paris] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/centreon/www/include/monitoring/objectDetails/serviceDetails.php on line 76
[14-Oct-2019 14:14:30 Europe/Paris] PHP Notice:  Undefined variable: l_rndcolor in /usr/share/centreon/www/class/centreonGraphNg.class.php on line 1119
[14-Oct-2019 14:20:30 Europe/Paris] PHP Notice:  Undefined variable: l_rndcolor in /usr/share/centreon/www/class/centreonGraphNg.class.php on line 1119
[14-Oct-2019 14:22:08 Europe/Paris] PHP Notice:  Undefined variable: l_rndcolor in /usr/share/centreon/www/class/centreonGraphNg.class.php on line 1119
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 1847
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 1905
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 2108
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 2148
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 2463
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 2527
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 1847
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 1905
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 2108
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 2148
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 2463
[14-Oct-2019 14:33:03 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php on line 2527
[15-Oct-2019 12:17:56 Europe/Paris] PHP Notice:  Undefined variable: l_rndcolor in /usr/share/centreon/www/class/centreonGraphNg.class.php on line 1119
[15-Oct-2019 17:01:07 Europe/Paris] PHP Notice:  Undefined variable: l_rndcolor in /usr/share/centreon/www/class/centreonGraphNg.class.php on line 1119
[15-Oct-2019 17:12:15 Europe/Paris] PHP Warning:  Illegal string offset 'command_type' in /usr/share/centreon/www/include/configuration/configObject/command/minCommand.php on line 132
[15-Oct-2019 17:26:50 Europe/Paris] PHP Warning:  Illegal string offset 'command_type' in /usr/share/centreon/www/include/configuration/configObject/command/minCommand.php on line 132
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[16-Oct-2019 13:45:18 Europe/Paris] PHP Notice:  Undefined index: service_activate in /usr/share/centreon/www/api/class/centreon_configuration_service.class.php on line 296
[17-Oct-2019 09:45:10 Europe/Paris] PHP Warning:  require(/usr/share/centreon/vendor/composer/../symfony/polyfill-php73/bootstrap.php): failed to open stream: No such file or directory in /usr/share/centreon/vendor/composer/autoload_real.php on line 70
[17-Oct-2019 09:45:10 Europe/Paris] PHP Warning:  require(/usr/share/centreon/vendor/composer/../symfony/polyfill-php73/bootstrap.php): failed to open stream: No such file or directory in /usr/share/centreon/vendor/composer/autoload_real.php on line 70
[17-Oct-2019 09:45:10 Europe/Paris] PHP Fatal error:  require(): Failed opening required '/usr/share/centreon/vendor/composer/../symfony/polyfill-php73/bootstrap.php' (include_path='/usr/share/centreon/vendor/pear/pear_exception:/usr/share/centreon/vendor/pear/console_getopt:/usr/share/centreon/vendor/pear/pear-core-minimal/src:/usr/share/centreon/www/class:/usr/share/centreon/www/lib:.:/opt/rh/rh-php72/root/usr/share/pear:/opt/rh/rh-php72/root/usr/share/php') in /usr/share/centreon/vendor/composer/autoload_real.php on line 70
[17-Oct-2019 11:19:52 Europe/Paris] PHP Notice:  Undefined index: current in /usr/share/centreon/www/install/step_upgrade/process/process_step5.php on line 77
[17-Oct-2019 12:25:30 Europe/Paris] PHP Notice:  Undefined variable: l_rndcolor in /usr/share/centreon/www/class/centreonGraphNg.class.php on line 1119
```

**Comment by mickaeldecastro** [comment]
I update database manually referring to the commit and it seems ok now for the field missing. 

I alway have the sh error with debug option.

**Comment by lpinsivy** [comment]
Should be fixed
