### ISSUE TITLE
Getting a blank screen after configuring Keycloak Auth

### ISSUE THREAD

**Issue by srinathman** [centreon/centreon#8098]
For the RPM based systems

-- Copy/Paste the result of the following command --
```
# rpm -qa | grep centreon
centreon-widget-httploader-19.10.0-1.el7.centos.noarch
centreon-connector-ssh-19.10.0-1.el7.centos.x86_64
centreon-auto-discovery-server-19.10.0-2.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20191016-111959.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20191016-111959.el7.centos.noarch
centreon-widget-tactical-overview-19.10.0-1.el7.centos.noarch
centreon-widget-graph-monitoring-19.10.0-1.el7.centos.noarch
centreon-license-manager-common-19.10.0-1.el7.centos.noarch
centreon-nrpe-plugin-2.15-4.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20191016-111959.el7.centos.noarch
centreon-release-19.10-1.el7.centos.noarch
centreon-engine-extcommands-19.10.5-1.el7.centos.x86_64
centreon-widget-engine-status-19.10.0-1.el7.centos.noarch
centreon-trap-19.10.1-3.el7.centos.noarch
centreon-poller-centreon-engine-19.10.1-3.el7.centos.noarch
centreon-license-manager-19.10.0-1.el7.centos.noarch
centreon-19.10.1-3.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20191016-111959.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20191016-111959.el7.centos.noarch
centreon-broker-19.10.0-1.el7.centos.x86_64
centreon-broker-storage-19.10.0-1.el7.centos.x86_64
centreon-engine-daemon-19.10.5-1.el7.centos.x86_64
centreon-widget-hostgroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-19.10.0-1.el7.centos.noarch
centreon-widget-global-health-19.10.0-1.el7.centos.noarch
centreon-connector-perl-19.10.0-1.el7.centos.x86_64
centreon-database-19.10.1-3.el7.centos.noarch
centreon-pp-manager-19.10.0-5.el7.centos.noarch
centreon-fingerprint-19.10-1.el7.centos.x86_64
centreon-plugin-Hardware-Printers-Generic-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20191016-111959.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20191016-111959.el7.centos.noarch
centreon-clib-19.10.0-6.el7.centos.x86_64
centreon-nrpe-daemon-2.15-4.el7.centos.x86_64
centreon-broker-cbmod-19.10.0-1.el7.centos.x86_64
centreon-widget-grid-map-19.10.0-1.el7.centos.noarch
centreon-widget-service-monitoring-19.10.1-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-nrpe3-plugin-3.2.1-7.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Central-20191016-111959.el7.centos.noarch
centreon-common-19.10.1-3.el7.centos.noarch
centreon-engine-19.10.5-1.el7.centos.x86_64
centreon-web-19.10.1-3.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-19.10.0-1.el7.centos.noarch
centreon-connector-19.10.0-1.el7.centos.x86_64
centreon-base-config-centreon-engine-19.10.1-3.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20191016-111959.el7.centos.noarch
centreon-perl-libs-19.10.1-3.el7.centos.noarch
centreon-broker-core-19.10.0-1.el7.centos.x86_64
centreon-broker-cbd-19.10.0-1.el7.centos.x86_64
centreon-widget-host-monitoring-19.10.0-1.el7.centos.noarch

```

***Operating System***

* CentOS

***Browser used***

- [x ] Google Chrome
- [ x] Chromium

### Description

After enabling and setting up Keycloak parameters, I get a blank screen instead of login page.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. Admistration -> Centreon UI
3. Under Authentication by Keycloak:
 3.1. Enabled Keycloak authentication
 3.2 Set to Mixed Mode
 3.3. Set all other parameters except tuster and blacklist client addresses (left empty)

### Describe the received result
Blank page instead Login form

### Describe the expected result
Login form + Login with keycloak button

### Logs

**PHP error logs**

```
[06-Nov-2019 20:45:18 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 in /usr/share/centreon/www/class/centreonDB.class.php:274
Stack trace:
#0 /usr/share/centreon/www/class/centreonACL.class.php(150): CentreonDB->query('SELECT update_a...')
#1 /usr/share/centreon/www/class/centreonACL.class.php(1364): CentreonACL->checkUpdateACL()
#2 /usr/share/centreon/www/api/class/centreon_topcounter.class.php(111): CentreonACL->getActions()
#3 /usr/share/centreon/www/api/class/centreon_topcounter.class.php(84): CentreonTopCounter->checkAccess()
#4 /usr/share/centreon/www/api/class/webService.class.php(338): CentreonTopCounter->__construct()
#5 /usr/share/centreon/www/api/internal.php(67): CentreonWebService::router(Object(Pimple\Container), Object(CentreonUser), true)
#6 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 274

**Comment by srinathman** [comment]
As an additional info, the situation above creates one or more sessions where user_id is NULL

```
MariaDB [centreon]> select id, session_id, user_id, current_page  from session ;
+------+----------------------------+---------+--------------+
| id   | session_id                 | user_id | current_page |
+------+----------------------------+---------+--------------+
| 2472 | m7j4iocuqbgvpnjbsoj3rjfj5k |     108 |            1 |
| 2473 | 41ksqa4nvf6v0lc95ahho77ojc |      19 |        50110 |
| 2512 | ropnrdo4boi1gg78fp2asg0obb |    NULL |            1 |
| 2513 | vjb6po4opq267djj5ahtrssiok |    NULL |            1 |
+------+----------------------------+---------+--------------+
4 rows in set (0.00 sec)
