### ISSUE TITLE
[LDAP] Centreon 19.04/19.10 - LDAP not working after upgrading from 18.10 to 19.04/19.10

### ISSUE THREAD

**Issue by romaincco** [centreon/centreon#8485]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the deb based systems

From sources : 
Centreon Engine 19.10.13
Centreon Broker 19.10.3
Centreon 19.10.10 (commit 98cbed5e4)
mariadb  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

***Operating System***

Debian 10

***Browser used***

- [x] Google Chrome
- [x] Firefox

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

VMWare 6.7.0

### Description

After updrading from 18.10 to 19.04 to 19.10, I can't login anymore with LDAP accounts, neither can I access LDAP configuration page.
If I go the the users settings, there is no users listed, even though users are in mysql database.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. I go to the LDAP settings
3. I go to the users settings

### Describe the received result

Pages are blank, I can't log in as LDAP users

### Describe the expected result

Users and LDAP settings should appears, LDAP account should be working

### Logs

**PHP error logs**

When accessing LDAP settings page : 
```
[27-Mar-2020 16:35:21 Europe/Paris] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ar_sync_base_date' in 'field list' in /usr/share/centreon/www/class/centreonDB.class.php:274
Stack trace:
#0 /usr/share/centreon/www/class/centreonLDAP.class.php(1401): CentreonDB->query()
#1 /usr/share/centreon/www/include/Administration/parameters/ldap/list.php(61): CentreonLdapAdmin->getLdapConfigurationList()
#2 /usr/share/centreon/www/include/Administration/parameters/ldap/ldap.php(60): include('/usr/share/cent...')
#3 /usr/share/centreon/www/include/Administration/parameters/parameters.php(75): require_once('/usr/share/cent...')
#4 /usr/share/centreon/www/main.get.php(248): include_once('/usr/share/cent...')
#5 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 274
```

When logging in as LDAP user  : 
```
[27-Mar-2020 16:39:19 Europe/Paris] PHP Fatal error:  Uncaught Exception: Error while getting automatic synchronization value for LDAP Id : 1 in /usr/share/centreon/www/class/centreonLDAP.class.php:968
Stack trace:
#0 /usr/share/centreon/www/class/centreonAuth.LDAP.class.php(266): CentreonLDAP->isSyncNeededAtLogin()
#1 /usr/share/centreon/www/class/centreonAuth.LDAP.class.php(149): CentreonAuthLDAP->updateUserDn()
#2 /usr/share/centreon/www/class/centreonAuth.class.php(190): CentreonAuthLDAP->checkPassword()
#3 /usr/share/centreon/www/class/centreonAuth.SSO.class.php(216): CentreonAuth->checkPassword()
#4 /usr/share/centreon/www/class/centreonAuth.class.php(313): CentreonAuthSSO->checkPassword()
#5 /usr/share/centreon/www/class/centreonAuth.class.php(121): CentreonAuth->checkUser()
#6 /usr/share/centreon/www/class/centreonAuth.SSO.class.php(129): CentreonAuth->__construct()
#7 /usr/share/centreon/www/include/core/login/processLogin.php(90): CentreonAuthSSO->__construct()
#8 /usr/share/centreon/www/include/core/login/login.php(68): require_once('/usr/share/cent.. in /usr/share/centreon/www/class/centreonLDAP.class.php on line 968
```

### Additional relevant information (e.g. frequency, ...)

It seems like createTables.sql did not work.
There is no column ar_sync_base_date in table auth_ressource
There is no column ldap_auto_sync and ldap_sync_interval in table auth_ressource_info
There is no column contact_ldap_required_sync and contact_ldap_last_sync in table contact

**Comment by romaincco** [comment]
I restored a 19.04 snapshot (updated from 18.10) and the problem is happening aswell.

**Comment by romaincco** [comment]
I did the process again to get more infos (18.10 > 19.10), here is a log regarding the LDAP SQL update :
```
[30-Mar-2020 13:29:27 Europe/Paris] PHP Notice:  Undefined variable: needToUpdateValues in /usr/share/centreon/www/install/php/Update-19.04.4.php on line 58
[30-Mar-2020 13:29:38 Europe/Paris] PHP Notice:  Undefined variable: needToUpdateValues in /usr/share/centreon/www/install/php/Update-19.10.0-beta.3.php on line 74
```

**Comment by romaincco** [comment]
```
MySQL: Error Code: 1118 Row size too large (> 8126)
```
Disabling innodb strict mode in mysql configuration makes ALTER query going through, not really a solution but I don't think you can change row size after the instance is initialized
