### ISSUE TITLE
Downtime and Acknowledge doesn't work since 20.10

### ISSUE THREAD

**Issue by AimPython** [centreon/centreon#9402]
# BUG REPORT INFORMATION

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
centreon-20.10.1-9.el7.centos.noarch
centreon-auto-discovery-server-20.10.2-1.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.1-9.el7.centos.noarch
centreon-broker-20.10.2-1.el7.centos.x86_64
centreon-broker-cbd-20.10.2-1.el7.centos.x86_64
centreon-broker-cbmod-20.10.2-1.el7.centos.x86_64
centreon-broker-core-20.10.2-1.el7.centos.x86_64
centreon-broker-storage-20.10.2-1.el7.centos.x86_64
centreon-clib-20.10.0-2.el7.centos.x86_64
centreon-common-20.10.1-9.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-database-20.10.1-9.el7.centos.noarch
centreon-engine-20.10.1-1.el7.centos.x86_64
centreon-engine-daemon-20.10.1-1.el7.centos.x86_64
centreon-engine-extcommands-20.10.1-1.el7.centos.x86_64
centreon-gorgone-20.10.1-5.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.1-5.el7.centos.noarch
centreon-license-manager-20.10.1-1.el7.centos.noarch
centreon-license-manager-common-20.10.1-1.el7.centos.noarch
centreon-perl-libs-20.10.1-9.el7.centos.noarch
centreon-poller-centreon-engine-20.10.1-9.el7.centos.noarch
centreon-pp-manager-20.10.0-1.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.1-9.el7.centos.noarch
centreon-web-20.10.1-9.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch

For the deb based systems

-- Copy/Paste the result of the following command --
MariaDB-client.x86_64                10.3.25-1.el7.centos       @centreon-stable
MariaDB-common.x86_64                10.3.25-1.el7.centos       @centreon-stable
MariaDB-compat.x86_64                10.3.25-1.el7.centos       @centreon-stable
MariaDB-server.x86_64                10.3.25-1.el7.centos       @centreon-stable
MariaDB-shared.x86_64                10.3.25-1.el7.centos       @centreon-stable
centreon.noarch                      20.10.1-9.el7.centos       @centreon-stable-noarch
centreon-auto-discovery-server.noarch
                                     20.10.2-1.el7.centos       @centreon-stable-noarch
centreon-base-config-centreon-engine.noarch
                                     20.10.1-9.el7.centos       @centreon-stable-noarch
centreon-broker.x86_64               20.10.2-1.el7.centos       @centreon-stable
centreon-broker-cbd.x86_64           20.10.2-1.el7.centos       @centreon-stable
centreon-broker-cbmod.x86_64         20.10.2-1.el7.centos       @centreon-stable
centreon-broker-core.x86_64          20.10.2-1.el7.centos       @centreon-stable
centreon-broker-storage.x86_64       20.10.2-1.el7.centos       @centreon-stable
centreon-clib.x86_64                 20.10.0-2.el7.centos       @centreon-stable
centreon-common.noarch               20.10.1-9.el7.centos       @centreon-stable-noarch
centreon-connector.x86_64            20.10.0-2.el7.centos       @centreon-stable
centreon-connector-perl.x86_64       20.10.0-2.el7.centos       @centreon-stable
centreon-connector-ssh.x86_64        20.10.0-2.el7.centos       @centreon-stable
centreon-database.noarch             20.10.1-9.el7.centos       @centreon-stable-noarch
centreon-engine.x86_64               20.10.1-1.el7.centos       @centreon-stable
centreon-engine-daemon.x86_64        20.10.1-1.el7.centos       @centreon-stable
centreon-engine-extcommands.x86_64   20.10.1-1.el7.centos       @centreon-stable
centreon-gorgone.noarch              20.10.1-5.el7.centos       @centreon-stable-noarch
centreon-gorgone-centreon-config.noarch
                                     20.10.1-5.el7.centos       @centreon-stable-noarch
centreon-license-manager.noarch      20.10.1-1.el7.centos       @centreon-stable-noarch
centreon-license-manager-common.noarch
                                     20.10.1-1.el7.centos       @centreon-stable-noarch
centreon-perl-libs.noarch            20.10.1-9.el7.centos       @centreon-stable-noarch
centreon-plugin-Applications-Databases-Mysql.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Applications-Monitoring-Centreon-Central.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Applications-Monitoring-Centreon-Database.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Applications-Protocol-Dns.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ftp.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Applications-Protocol-Http.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ldap.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Hardware-Printers-Generic-Snmp.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Network-Cisco-Standard-Snmp.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Operatingsystems-Linux-Snmp.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-plugin-Operatingsystems-Windows-Snmp.noarch
                                     20201211-091649.el7.centos @centreon-stable-noarch
centreon-poller-centreon-engine.noarch
                                     20.10.1-9.el7.centos       @centreon-stable-noarch
centreon-pp-manager.noarch           20.10.0-1.el7.centos       @centreon-stable-noarch
centreon-release.noarch              20.10-2.el7.centos         @/centreon-release-20.10-2.el7.centos.noarch
centreon-trap.noarch                 20.10.1-9.el7.centos       @centreon-stable-noarch
centreon-web.noarch                  20.10.1-9.el7.centos       @centreon-stable-noarch
centreon-widget-engine-status.noarch 20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-global-health.noarch 20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-graph-monitoring.noarch
                                     20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-grid-map.noarch      20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-host-monitoring.noarch
                                     20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-hostgroup-monitoring.noarch
                                     20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-httploader.noarch    20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-live-top10-cpu-usage.noarch
                                     20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-live-top10-memory-usage.noarch
                                     20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-service-monitoring.noarch
                                     20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-servicegroup-monitoring.noarch
                                     20.10.0-5.el7.centos       @centreon-stable-noarch
centreon-widget-tactical-overview.noarch
                                     20.10.0-5.el7.centos       @centreon-stable-noarch
galera.x86_64                        25.3.30-1.el7.centos       @centreon-stable
libssh.x86_64                        0.9.4-1.el7                @centreon-stable
nagios-common.x86_64                 4.4.5-7.el7                @centreon-stable
nagios-plugins.x86_64                2.3.3-2.el7                @centreon-stable
nagios-plugins-dhcp.x86_64           2.3.3-2.el7                @centreon-stable
nagios-plugins-icmp.x86_64           2.3.3-2.el7                @centreon-stable
perl-Libssh-Session.x86_64           0.8-2.el7                  @centreon-stable

***Operating System***

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

***Browser used***

- [ ] Firefox

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

Nutanix

-- Describe the encountered issue --

Hello,

Since the update of Centreon from 19.04 to 20.10 I no longer have the possibility to add or delete a Downtime or an Acknowledge.

I can't find anything special in the logs or maybe I'm not looking in the right place.

Maybe a problem of right on a file, but I don't know which one.

I have read the other issues but not knowing very well how Centreon works and not being a Linux expert, I'm having a little trouble.

1. I logged in Centreon
2. I reached Resource Status
3. I check a host
4. I press Downtime or Acknowledge
5. Put a message

### Describe the received result

No active changes

### Describe the expected result

Host is Acknowledged or Downtimed

### Logs

**PHP error logs**

#1 /usr/share/centreon/www/include/options/accessLists/groupsACL/groupsConfig.php(99): multipleGroupInDB(Array, Array)
#2 /usr/share/centreon/www/main.get.php(257): include_once('/usr/share/cent...')
#3 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 274
[08-Jan-2021 09:03:00 Europe/Paris] [critical] Uncaught PHP Exception Centreon\Infrastructure\Service\Exception\NotFoundException: "Session not found" at /usr/share/centreon/src/Security/SessionAPIAuthenticator.php line 172

[12-Jan-2021 09:34:29 Europe/Paris] [critical] Uncaught PHP Exception Centreon\Infrastructure\Service\Exception\NotFoundException: "Session not found" at /usr/share/centreon/src/Security/SessionAPIAuthenticator.php line 172

[13-Jan-2021 08:39:09 Europe/Paris] [critical] Uncaught PHP Exception Centreon\Infrastructure\Service\Exception\NotFoundException: "Session not found" at /usr/share/centreon/src/Security/SessionAPIAuthenticator.php line 172

**Comment by lpinsivy** [comment]
Hi, did you check if gorgoned daemon is running?

**Comment by AimPython** [comment]
Hi, thanks for reply

Redirecting to /bin/systemctl status gorgoned.service
● gorgoned.service - Centreon Gorgone
   Loaded: loaded (/etc/systemd/system/gorgoned.service; enabled; vendor preset: disabled)
   Active: active (running) since lun. 2021-01-18 09:21:03 CET; 1 weeks 1 days ago
 Main PID: 790 (perl)
   CGroup: /system.slice/gorgoned.service
           ├─ 790 /usr/bin/perl /usr/bin/gorgoned --config=/etc/centreon-gorgone/config.yaml --logfile=/var/log/centreon-gorgone/gorgoned.log --severity=inf...
           ├─ 828 gorgone-nodes
           ├─ 831 gorgone-dbcleaner
           ├─ 832 gorgone-autodiscovery
           ├─ 839 gorgone-cron
           ├─ 840 gorgone-engine
           ├─ 847 gorgone-statistics
           ├─ 848 gorgone-action
           ├─ 861 gorgone-httpserver
           ├─ 862 gorgone-legacycmd
           ├─4038 gorgone-proxy
           ├─4047 gorgone-proxy
           ├─4054 gorgone-proxy
           ├─4057 gorgone-proxy
           └─4071 gorgone-proxy

**Comment by AimPython** [comment]
Hello,

In the gorgoned logs, when I make an acknowledgement I get this result:

Something is trying to connect with credentials in clear text, but they don't exist anymore (credentials of first Centreon installation). I don't know if it can be related.


2021-02-25 12:05:27 - DEBUG - [autodiscovery] -class- host discovery - check centreon module installed
2021-02-25 12:05:27 - DEBUG - == Info: Found bundle for host 127.0.0.1: 0xc412980
2021-02-25 12:05:27 - DEBUG - == Info: Connection 25963 seems to be dead!
2021-02-25 12:05:27 - DEBUG - == Info: Closing connection 25963
2021-02-25 12:05:27 - DEBUG - == Info: Connection 25964 seems to be dead!
2021-02-25 12:05:27 - DEBUG - == Info: Closing connection 25964
2021-02-25 12:05:27 - DEBUG - == Info: About to connect() to 127.0.0.1 port 80 (#25965)
2021-02-25 12:05:27 - DEBUG - == Info:   Trying 127.0.0.1...
2021-02-25 12:05:27 - DEBUG - == Info: Connected to 127.0.0.1 (127.0.0.1) port 80 (#25965)
2021-02-25 12:05:27 - DEBUG - => Send header: POST /centreon/api/beta/login HTTP/1.1
Host: 127.0.0.1
Accept: */*
Content-Type: application/json; charset=utf-8
Accept-Type: application/json; charset=utf-8
Content-Length: 68

2021-02-25 12:05:27 - DEBUG - => Send data: {"security":{"credentials":{"password":"XXXXXX","login":"XXXXXXX"}}}
2021-02-25 12:05:27 - DEBUG - == Info: upload completely sent off: 68 out of 68 bytes
2021-02-25 12:05:27 - DEBUG - => Recv header: HTTP/1.1 302 Found
2021-02-25 12:05:27 - DEBUG - => Recv header: Date: Thu, 25 Feb 2021 11:05:27 GMT
2021-02-25 12:05:27 - DEBUG - => Recv header: Server: Apache
2021-02-25 12:05:27 - DEBUG - => Recv header: Location: https://127.0.0.1/centreon/api/beta/login
2021-02-25 12:05:27 - DEBUG - => Recv header: Content-Length: 225
2021-02-25 12:05:27 - DEBUG - => Recv header: Content-Type: text/html; charset=iso-8859-1
2021-02-25 12:05:27 - DEBUG - => Recv header:
2021-02-25 12:05:27 - DEBUG - == Info: Ignoring the response-body
2021-02-25 12:05:27 - DEBUG - => Recv data: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://127.0.0.1/centreon/api/beta/login">here</a>.</p>
</body></html>
2021-02-25 12:05:27 - DEBUG - == Info: Connection #25965 to host 127.0.0.1 left intact
2021-02-25 12:05:27 - DEBUG - == Info: Issue another request to this URL: 'https://127.0.0.1/centreon/api/beta/login'
2021-02-25 12:05:27 - DEBUG - == Info: Found bundle for host 127.0.0.1: 0xc4326a0
2021-02-25 12:05:27 - DEBUG - == Info: About to connect() to 127.0.0.1 port 443 (#25966)
2021-02-25 12:05:27 - DEBUG - == Info:   Trying 127.0.0.1...
2021-02-25 12:05:27 - DEBUG - == Info: Connected to 127.0.0.1 (127.0.0.1) port 443 (#25966)
2021-02-25 12:05:27 - DEBUG - == Info: warning: ignoring value of ssl.verifyhost
2021-02-25 12:05:27 - DEBUG - == Info: skipping SSL peer certificate verification
2021-02-25 12:05:27 - DEBUG - == Info: SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
2021-02-25 12:05:27 - DEBUG - == Info: Server certificate:
2021-02-25 12:05:27 - DEBUG - == Info:  subject: CN=*.XXXXXXX.com,OU=XXXX XXXXXXXXX,O=XXXXX XXXXX,STREET=XXXXXXXXXXXXXXXXXX,L=XXXXXXXXXXXXXX,ST=XXXXXe,postalCode=XXXX,C=FR
2021-02-25 12:05:27 - DEBUG - == Info:  start date: dÃ©c. 22 00:00:00 2020 GMT
2021-02-25 12:05:27 - DEBUG - == Info:  expire date: janv. 22 23:59:59 2022 GMT
2021-02-25 12:05:27 - DEBUG - == Info:  common name: *.XXXXXXX.com
2021-02-25 12:05:27 - DEBUG - == Info:  issuer: CN=Sectigo RSA Organization Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB
2021-02-25 12:05:27 - DEBUG - => Send header: POST /centreon/api/beta/login HTTP/1.1
Host: 127.0.0.1
Accept: */*
Content-Type: application/json; charset=utf-8
Accept-Type: application/json; charset=utf-8
Content-Length: 68

2021-02-25 12:05:27 - DEBUG - => Send data: {"security":{"credentials":{"password":"XXXXXX","login":"XXXXXXXX"}}}
2021-02-25 12:05:27 - DEBUG - == Info: upload completely sent off: 68 out of 68 bytes
2021-02-25 12:05:27 - DEBUG - => Recv header: HTTP/1.1 401 Unauthorized
2021-02-25 12:05:27 - DEBUG - => Recv header: Date: Thu, 25 Feb 2021 11:05:27 GMT
2021-02-25 12:05:27 - DEBUG - => Recv header: Server: Apache
2021-02-25 12:05:27 - DEBUG - => Recv header: Cache-Control: no-cache, private
2021-02-25 12:05:27 - DEBUG - => Recv header: Api-Version: 2.0
2021-02-25 12:05:27 - DEBUG - => Recv header: Upgrade: h2,h2c
2021-02-25 12:05:27 - DEBUG - => Recv header: Connection: Upgrade
2021-02-25 12:05:27 - DEBUG - => Recv header: Transfer-Encoding: chunked
2021-02-25 12:05:27 - DEBUG - => Recv header: Content-Type: application/json
2021-02-25 12:05:27 - DEBUG - => Recv header:
2021-02-25 12:05:27 - DEBUG - => Recv data: 2c
{"code":401,"message":"Invalid credentials"}
0

2021-02-25 12:05:27 - DEBUG - == Info: Connection #25966 to host 127.0.0.1 left intact
2021-02-25 12:05:27 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '401'] [message: 'Unauthorized']
2021-02-25 12:05:40 - DEBUG - [legacycmd] Processing file '/var/lib/centreon/centcore//external-cmd-1614251139,8543.cmd_read'
2021-02-25 12:05:40 - INFO - [legacycmd] Handling command 'EXTERNALCMD', Target: '1', Parameters: '[1614251139] ACKNOWLEDGE_SVC_PROBLEM;HGPADL14B;Disque Windows;1;0;1;admin;test'
2021-02-25 12:05:40 - DEBUG - [core] Message received - [ENGINECOMMAND] [efe3c7211e0cfe68a867dae9bbc6e0c5f2e2a6405ac31957901cc5f9d42e4b1fcdb3ff5afff1232cb68ab12cde005dd6f4f348ec5f2ec3ecb921af7a5293                            7d10] [1] {"content":{"command_file":"/var/lib/centreon-engine/rw/centengine.cmd","commands":["[1614251139] ACKNOWLEDGE_SVC_PROBLEM;HGPADL14B;Disque Windows;1;0;1;admin;test"]}}
2021-02-25 12:05:40 - DEBUG - [engine] Event: [ENGINECOMMAND] [efe3c7211e0cfe68a867dae9bbc6e0c5f2e2a6405ac31957901cc5f9d42e4b1fcdb3ff5afff1232cb68ab12cde005dd6f4f348ec5f2ec3ecb921af7a52937d10] [] {                            "content":{"command_file":"/var/lib/centreon-engine/rw/centengine.cmd","commands":["[1614251139] ACKNOWLEDGE_SVC_PROBLEM;HGPADL14B;Disque Windows;1;0;1;admin;test"]}}
2021-02-25 12:05:40 - DEBUG - [engine] Create sub-process
2021-02-25 12:05:40 - DEBUG - [legacycmd] Event: [ACK] [efe3c7211e0cfe68a867dae9bbc6e0c5f2e2a6405ac31957901cc5f9d42e4b1fcdb3ff5afff1232cb68ab12cde005dd6f4f348ec5f2ec3ecb921af7a52937d10] {"data":nul                            l,"code":0}
2021-02-25 12:05:40 - DEBUG - [core] Message received - [PUTLOG] [efe3c7211e0cfe68a867dae9bbc6e0c5f2e2a6405ac31957901cc5f9d42e4b1fcdb3ff5afff1232cb68ab12cde005dd6f4f348ec5f2ec3ecb921af7a52937d10] [                            ] {"etime":1614251140,"data":{"request_content":{"command_file":"/var/lib/centreon-engine/rw/centengine.cmd","commands":["[1614251139] ACKNOWLEDGE_SVC_PROBLEM;HGPADL14B;Disque Windows;1;0;1;admin;t                            est"]},"message":"commands processing has started"},"instant":null,"token":"efe3c7211e0cfe68a867dae9bbc6e0c5f2e2a6405ac31957901cc5f9d42e4b1fcdb3ff5afff1232cb68ab12cde005dd6f4f348ec5f2ec3ecb921af7a5                            2937d10","code":0}
2021-02-25 12:05:45 - ERROR - [engine] Receiving DIE: Timeout command at /usr/share/perl5/vendor_perl/gorgone/modules/centreon/engine/class.pm line 151.

2021-02-25 12:05:45 - ERROR - [engine] Receiving DIE: Timeout command at /usr/share/perl5/vendor_perl/gorgone/modules/centreon/engine/class.pm line 151.

2021-02-25 12:05:45 - ERROR - [engine] Submit engine command issue: Timeout command at /usr/share/perl5/vendor_perl/gorgone/modules/centreon/engine/class.pm line 151.

2021-02-25 12:05:45 - DEBUG - [core] Message received - [PUTLOG] [efe3c7211e0cfe68a867dae9bbc6e0c5f2e2a6405ac31957901cc5f9d42e4b1fcdb3ff5afff1232cb68ab12cde005dd6f4f348ec5f2ec3ecb921af7a52937d10] [                            ] {"etime":1614251145,"data":{"message":"submit engine command issue: Timeout command at /usr/share/perl5/vendor_perl/gorgone/modules/centreon/engine/class.pm line 151.\n"},"instant":null,"token":"                            efe3c7211e0cfe68a867dae9bbc6e0c5f2e2a6405ac31957901cc5f9d42e4b1fcdb3ff5afff1232cb68ab12cde005dd6f4f348ec5f2ec3ecb921af7a52937d10","code":1}
2021-02-25 12:05:45 - DEBUG - [core] Received SIGCLD signal (pid: 29838)

**Comment by AimPython** [comment]
The command in "/var/lib/centreon-engine/rw/centengine.cmd" looks like this "[1614255972] ACKNOWLEDGE_SVC_PROBLEM;HGPADL14;Windows disk;1;0;1;admin;test".

**Comment by AimPython** [comment]
Same after upgrading 20.04 to 21.04.

**Comment by lpinsivy** [comment]
Can you try to install gorgone on the poller and move from SSH to Gorgone communication?
