### ISSUE TITLE
[21.04.0] CLAPI import / export

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#9884]
Hi team,

I am migrating my objects exported by CLAPI 19.04.16 to my new platform running 21.04.0.
- When I start import I get the following output

```
Line 2 : Object already exists (Guest Menu)
Line 43 : Object already exists (Monitoring Menu)
Line 45 : Object not found:Poller/Remote Wizard
Line 46 : Object not found:Remote Wizard Step 2
Line 47 : Object not found:Remote Wizard Step 3
Line 48 : Object not found:Remote Wizard Final Step
Line 49 : Object not found:Poller Wizard Step 2
Line 50 : Object not found:Poller Wizard Step 3
Line 51 : Object not found:Poller Wizard Final Step
Line 133 : Object not found:Manager
Line 134 : Object not found:Plugin Packs
Line 151 : Object already exists (Guest Actions)
Line 160 : Object already exists (Monitoring Actions)
Line 168 : Unknown action:service_disacknowledgement
Line 177 : Unknown action:service_display_command
Line 181 : Unknown action:host_disacknowledgement
Line 203 : Unknown action:generate_cfg
Line 204 : Missing parameters
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'init_script' in 'field list' in /usr/share/centreon/www/class/centreonDB.class.php:275
Stack trace:
#0 /usr/share/centreon/lib/Centreon/Object/Object.php(179): CentreonDB->query('UPDATE nagios_s...', Array)
#1 /usr/share/centreon/www/class/centreon-clapi/centreonObject.class.php(365): Centreon_Object->update('1', Array)
#2 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(806): CentreonClapi\CentreonObject->setparam('Central;init_sc...')
#3 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(769): CentreonClapi\CentreonAPI->launchActionForImport()
#4 /usr/share/centreon/bin/centreon(196): CentreonClapi\CentreonAPI->import('/tmp/clapi-expo...')
#5 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 275
```
Seems like the new db structure is different now. 
What should be the best way to perform this migration?

- When I tried to slice clapi-export.txt to extract just the poller instances into pollers.txt and imported it I had this fault:
```
PHP Fatal error:  Uncaught Error: Class '\CentreonClapi\centreon' not found in /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php:934
Stack trace:
#0 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(799): CentreonClapi\CentreonAPI->iniObject('NSTANCE')
#1 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(769): CentreonClapi\CentreonAPI->launchActionForImport()
#2 /usr/share/centreon/bin/centreon(196): CentreonClapi\CentreonAPI->import('pollers.txt')
#3 {main}
  thrown in /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php on line 934
```
This error is caused by trying to import Central poller which already existed, but I thing 

> Class '\CentreonClapi\centreon' not found

 should not be the right error exception here

- When I tried to import broker, CLAPI attempts to update deprecated column **config_correlation_activate** from table cfg_centreonbroker
`CENTBROKERCFG;SETPARAM;central-broker-master;correlation_activate;0`

```
Line 416 : Object already exists (central-broker-master)
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config_correlation_activate' in 'field list' in /usr/share/centreon/www/class/centreonDB.class.php:275
Stack trace:
#0 /usr/share/centreon/lib/Centreon/Object/Object.php(179): CentreonDB->query('UPDATE cfg_cent...', Array)
#1 /usr/share/centreon/www/class/centreon-clapi/centreonObject.class.php(365): Centreon_Object->update('1', Array)
#2 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(806): CentreonClapi\CentreonObject->setparam('central-broker-...')
#3 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(769): CentreonClapi\CentreonAPI->launchActionForImport()
#4 /usr/share/centreon/bin/centreon(196): CentreonClapi\CentreonAPI->import('clapi-export.tx...')
#5 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 275
```

- In attempt to import Engine Configuration we have a deprecated field **use_check_result_path**
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'use_check_result_path' in 'field list' in /usr/share/centreon/www/class/centreonDB.class.php:275
Stack trace:
#0 /usr/share/centreon/lib/Centreon/Object/Object.php(179): CentreonDB->query('UPDATE cfg_nagi...', Array)
#1 /usr/share/centreon/www/class/centreon-clapi/centreonObject.class.php(365): Centreon_Object->update('1', Array)
#2 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(806): CentreonClapi\CentreonObject->setparam('Centreon Engine...')
#3 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(769): CentreonClapi\CentreonAPI->launchActionForImport()
#4 /usr/share/centreon/bin/centreon(196): CentreonClapi\CentreonAPI->import('clapi-export.tx...')
#5 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 275
```
- Importing Hosts causes CLAPI to update table host with deprecated column **host_vrml_image**
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'host_vrml_image' in 'field list' in /usr/share/centreon/www/class/centreonDB.class.php:275
Stack trace:
#0 /usr/share/centreon/lib/Centreon/Object/Object.php(179): CentreonDB->query('UPDATE host SET...', Array)
#1 /usr/share/centreon/www/class/centreon-clapi/centreonObject.class.php(365): Centreon_Object->update('40', Array)
#2 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(806): CentreonClapi\CentreonObject->setparam('TOWDA0PP001-CFT...')
#3 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(769): CentreonClapi\CentreonAPI->launchActionForImport()
#4 /usr/share/centreon/bin/centreon(196): CentreonClapi\CentreonAPI->import('clapi-export.tx...')
#5 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 275
```
- Same as when I import services I get unknown **service_con_image**
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'service_con_image' in 'field list' in /usr/share/centreon/www/class/centreonDB.class.php:276
Stack trace:
#0 /usr/share/centreon/lib/Centreon/Object/Object.php(179): CentreonDB->query('UPDATE service ...', Array)
#1 /usr/share/centreon/www/class/centreon-clapi/centreonObject.class.php(365): Centreon_Object->update('6972', Array)
#2 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(806): CentreonClapi\CentreonObject->setparam('CFTV;check icmp...')
#3 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(769): CentreonClapi\CentreonAPI->launchActionForImport()
#4 /usr/share/centreon/bin/centreon(196): CentreonClapi\CentreonAPI->import('saida.txt')
#5 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 276
```

**Comment by lpinsivy** [comment]
Hi @kozfelipe CLAPI will have incompatibility between major version but we used to fix a lot of issue with latest versions
